# Generated by Django 4.2.7 on 2023-11-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('numero_telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=100)),
                ('horario_atencion_inicio', models.TimeField()),
                ('horario_atencion_cierre', models.TimeField()),
            ],
            options={
                'db_table': 'restaurante',
            },
        ),
    ]
