# Generated by Django 4.2.7 on 2023-12-12 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_detallecompra_compra_inventario_and_more'),
        ('restaurante', '0002_compraproductos_detallecompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraproductos',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='compraproductos',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.DeleteModel(
            name='DetalleCompra',
        ),
    ]
