# Generated by Django 4.2.7 on 2023-12-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_compraproductos_cantidad_compraproductos_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compraproductos',
            name='proveedor',
        ),
    ]
