# Generated by Django 4.2.7 on 2023-12-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0005_ventaproducto_detalleventaproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaproducto',
            name='dinero_ingresado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
