# Generated by Django 4.2.7 on 2023-12-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0006_ventaproducto_dinero_ingresado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventaproducto',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
