# Generated by Django 4.2.7 on 2023-11-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_materia_prima_preparacion_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='preparacion',
        ),
        migrations.AddField(
            model_name='preparacion',
            name='item',
            field=models.ManyToManyField(blank=True, to='menu.item'),
        ),
    ]
