# Generated by Django 4.2.7 on 2023-11-27 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_item_preparacion_preparacion_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preparacion',
            name='item',
        ),
        migrations.AddField(
            model_name='preparacion',
            name='item',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Necesidad', to='menu.item'),
        ),
    ]
