# Generated by Django 4.2.7 on 2023-11-27 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_preparacion_item_preparacion_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparacion',
            name='item',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='menu.item'),
        ),
    ]
