# Generated by Django 4.2.7 on 2023-11-27 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_compra_inventario_compraproductos_and_more'),
        ('menu', '0005_alter_preparacion_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparacion',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.item'),
        ),
        migrations.AlterField(
            model_name='preparacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Necesidad', to='inventario.producto'),
        ),
    ]
