# Generated by Django 4.2.7 on 2023-12-12 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='compra_inventario',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='producto',
        ),
        migrations.DeleteModel(
            name='CompraProductos',
        ),
        migrations.DeleteModel(
            name='DetalleCompra',
        ),
    ]
